version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1
  
jobs:
  ci:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: build nuxt project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - save_cache:
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ~/node_modules
            - ~/.nuxt/dist
      - run:
          name: Run linter
          command:  yarn lint
  
  cypress:
    docker:
      - image: cypress/base:latest
    parallelism: 3
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: run E2E tests with cypress
          command:  yarn test:ci
      - store_test_results:
          path: cypress/results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  sonarcloud:
    docker:
      - image: node:latest
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  build-and-test:
    jobs:
      - ci
      - cypress:
          requires:
            - ci
          filters:
            branches:
              only:
                - main
                - staging
                - merge_requests
      - sonarcloud:
          context: Sonarcloud
          requires:
            - ci
          filters:
            branches:
              only:
                - main
                - staging
                - merge_requests